Description: Store logs
Resources:
  AuditBucket:
    Type: "AWS::S3::Bucket"
  AuditBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref AuditBucket
      PolicyDocument:
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudtrail.amazonaws.com"
            Action:
              - "s3:GetBucketAcl"
            Resource: !GetAtt AuditBucket.Arn
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudtrail.amazonaws.com"
            Action:
              - "s3:PutObject"
            Resource: !Join [ "", [!GetAtt AuditBucket.Arn,"/AWSLogs/", !Ref "AWS::AccountId" ,"/*"]]
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
Outputs:
  AuditBucketName:
    Description: Logs Bucket Name
    Value: !Ref AuditBucket
    Export:
      Name: logs-bucket
