Description: Sample Echo Application
Resources:
  FnLechoRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns: ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]
  FnLecho:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Code: ./target/lecho.zip
      MemorySize: 128
      Timeout: 5
      Role: !GetAtt FnLechoRole.Arn
  EchoAPI: 
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "EchoAPI"
      FailOnWarnings: true
  EchoResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref EchoAPI
      ParentId: !GetAtt EchoAPI.RootResourceId
      PathPart: '{proxy+}'
  EchoMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref EchoAPI
      ResourceId: !Ref EchoResource
      HttpMethod: ANY
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FnLecho.Arn}/invocations
  EchoDeployment: 
    DependsOn: "EchoMethod"
    Type: "AWS::ApiGateway::Deployment"
    Properties: 
      RestApiId: !Ref EchoAPI
      StageName: echoDummyDeploymentStage
  EchoStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: echoStage
      RestApiId: !Ref EchoAPI
      DeploymentId: !Ref EchoDeployment
  FnLechoPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt FnLecho.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join [ "", [ "arn:aws:execute-api:", !Ref "AWS::Region",":", !Ref "AWS::AccountId", ":",!Ref "EchoAPI","/*/*/*" ]]
Outputs:
  EchoDistributionDomainName:
    Value: !GetAtt EchoDomainName.DistributionDomainName