Description: Security Resources
Parameters:
  AdminPassword:
    Type: String
Resources:
  AdminUser:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./admin-user/admin-user.yaml  
      Parameters:
        AdminPassword: !Ref AdminPassword 
  AuditTrail:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./audit-trail/audit-trail.yaml
  NoRoot:
    Type: AWS::CloudFormation::Stack
    DependsOn: AuditTrail
    Properties:
      TemplateURL: ./no-root/target/no-root.out.yaml