Description: Log AWS API calls for auditing
Resources:
  AuditGroup:
    Type: "AWS::Logs::LogGroup"
  AuditRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudtrail.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "logs:CreateLogStream"
                Resource:
                  - !Sub ${AuditGroup.Arn}
              -
                Effect: "Allow"
                Action: "logs:PutLogEvents"
                Resource:
                  - !Sub ${AuditGroup.Arn}
  AuditTrail:
    Type: "AWS::CloudTrail::Trail"
    Properties:
      CloudWatchLogsLogGroupArn: !GetAtt AuditGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt AuditRole.Arn
      S3BucketName: !ImportValue logs-bucket
      IsLogging: true
Outputs:
  AuditGroupOut:
    Description: Log group for trail logs
    Value: !Ref AuditGroup
    Export:
      Name: audit-loggroup
